name: Python package

on:
  push:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/python-app.yml'
      - 'guachi/**'
      - 'tests/**'
  pull_request:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/python-app.yml'
      - 'guachi/**'
      - 'tests/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: [3.9, 3.10, 3.11]
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest
      - name: Run tests
        run: |
          PYTHONPATH=upgraded pytest upgraded/guachi/tests/ --maxfail=5 --disable-warnings -v
